[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://poker-history-backend-e54899b9ba1c.herokuapp.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 